In [2]:
print("Hello, Python!")

Hello, Python!

In [3]:
import pandas as pd


url = "https://kworb.net/ww/"


tables = pd.read_html(url)


print(f"Total tables found: {len(tables)}")


df = tables[0]


df.head()

Total tables found: 1

,Pos,P+,Artist and Title,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP
0,1,=,Shakira & Burna Boy - Dai Dai,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0
1,2,+2,"HUGEL, Imael Angel & Ultra Naté - Movin' To Th...",44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN
2,3,+4,Madonna - Danceteria,2,3,(x1),11086,172,0.022,60.0,9.0,28.0,6.0,NaN
3,4,-2,Madonna & Sabrina Carpenter - Bring Your Love,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0
4,5,+3,Robyn - Dancing On My Own,64,3,(x3),9671,-952,0.611,17.0,8.0,16.0,2.0,NaN

In [4]:
print(df.columns)
df.head(10)

Index(['Pos', 'P+', 'Artist and Title', 'Days', 'Pk', '(x?)', 'Pts', 'Pts+',
       'TPts', 'US', 'UK', 'DE', 'AU', 'JP'],
      dtype='str')

,Pos,P+,Artist and Title,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP
0,1,=,Shakira & Burna Boy - Dai Dai,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0
1,2,+2,"HUGEL, Imael Angel & Ultra Naté - Movin' To Th...",44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN
2,3,+4,Madonna - Danceteria,2,3,(x1),11086,172,0.022,60.0,9.0,28.0,6.0,NaN
3,4,-2,Madonna & Sabrina Carpenter - Bring Your Love,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0
4,5,+3,Robyn - Dancing On My Own,64,3,(x3),9671,-952,0.611,17.0,8.0,16.0,2.0,NaN
5,6,=,"Céline Dion - Bonjour, Pardon, Merci",2,6,NaN,9391,-1918,0.021,134.0,28.0,6.0,123.0,NaN
6,7,+3,"Taylor Swift - I Knew It, I Knew You",30,1,(x7),8843,1229,0.400,9.0,5.0,139.0,5.0,31.0
7,8,-5,Madonna - Love Sensation,30,2,(x6),8668,-5775,0.229,35.0,24.0,26.0,42.0,NaN
8,9,-4,Madonna - I Feel So Free,45,1,(x4),8459,-4392,0.351,37.0,16.0,48.0,93.0,NaN
9,10,+1,Ariana Grande - hate that i made you love me,37,1,(x7),7682,114,0.456,51.0,22.0,129.0,22.0,NaN

We extract the artist and title data to split artist and title

In [9]:
df[['Artist', 'Title']] = df['Artist and Title'].str.split(' - ', n=1, expand=True)

df[['Artist', 'Title']]

                              Artist                    Title
0                Shakira & Burna Boy                  Dai Dai
1    HUGEL, Imael Angel & Ultra Naté        Movin' To The Sun
2                            Madonna               Danceteria
3        Madonna & Sabrina Carpenter          Bring Your Love
4                              Robyn        Dancing On My Own
..                               ...                      ...
195                    Kenshi Yonezu                 IRIS OUT
196                       Toby Keith          Made In America
197                 Momoiro Clover Z      Kaishin No Ichigeki
198                   Angelina Mango            Canto d’amore
199                     Eddie Dalton  Somewhere Along The Way

[200 rows x 2 columns]

Remove whitespace from the strings in these columns

In [12]:
df['Artist'] = df['Artist'].str.strip()
df['Title'] = df['Title'].str.strip()

df[['Artist', 'Title']]

                              Artist                    Title
0                Shakira & Burna Boy                  Dai Dai
1    HUGEL, Imael Angel & Ultra Naté        Movin' To The Sun
2                            Madonna               Danceteria
3        Madonna & Sabrina Carpenter          Bring Your Love
4                              Robyn        Dancing On My Own
..                               ...                      ...
195                    Kenshi Yonezu                 IRIS OUT
196                       Toby Keith          Made In America
197                 Momoiro Clover Z      Kaishin No Ichigeki
198                   Angelina Mango            Canto d’amore
199                     Eddie Dalton  Somewhere Along The Way

[200 rows x 2 columns]

We're all good!

In [24]:
print(df['Title'].isna().sum())

0

In [27]:
df

,Pos,P+,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP,Artist,Title
0,1,=,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0,Shakira & Burna Boy,Dai Dai
1,2,+2,44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN,"HUGEL, Imael Angel & Ultra Naté",Movin' To The Sun
2,3,+4,2,3,(x1),11086,172,0.022,60.0,9.0,28.0,6.0,NaN,Madonna,Danceteria
3,4,-2,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0,Madonna & Sabrina Carpenter,Bring Your Love
4,5,+3,64,3,(x3),9671,-952,0.611,17.0,8.0,16.0,2.0,NaN,Robyn,Dancing On My Own
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,NEW,201,28,NaN,1066,1066,0.391,NaN,NaN,NaN,NaN,27.0,Kenshi Yonezu,IRIS OUT
196,197,NEW,2,181,NaN,1062,636,0.049,22.0,NaN,NaN,NaN,NaN,Toby Keith,Made In America
197,198,-62,2,136,NaN,1062,-306,0.002,NaN,NaN,NaN,NaN,22.0,Momoiro Clover Z,Kaishin No Ichigeki
198,199,NEW,9,53,NaN,1061,229,0.024,NaN,NaN,NaN,NaN,NaN,Angelina Mango,Canto d’amore
199,200,-21,73,11,NaN,1057,-89,0.261,63.0,82.0,NaN,NaN,NaN,Eddie Dalton,Somewhere Along The Way

We create a column where all text is lowercase for matching purposes (the logic of the project starts here)

In [30]:
df['Artist_clean'] = df['Artist'].str.lower().str.strip()
df['Title_clean'] = df['Title'].str.lower().str.strip()

df

,Pos,P+,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP,Artist,Title,Artist_clean,Title_clean
0,1,=,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0,Shakira & Burna Boy,Dai Dai,shakira & burna boy,dai dai
1,2,+2,44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN,"HUGEL, Imael Angel & Ultra Naté",Movin' To The Sun,"hugel, imael angel & ultra naté",movin' to the sun
2,3,+4,2,3,(x1),11086,172,0.022,60.0,9.0,28.0,6.0,NaN,Madonna,Danceteria,madonna,danceteria
3,4,-2,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0,Madonna & Sabrina Carpenter,Bring Your Love,madonna & sabrina carpenter,bring your love
4,5,+3,64,3,(x3),9671,-952,0.611,17.0,8.0,16.0,2.0,NaN,Robyn,Dancing On My Own,robyn,dancing on my own
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,NEW,201,28,NaN,1066,1066,0.391,NaN,NaN,NaN,NaN,27.0,Kenshi Yonezu,IRIS OUT,kenshi yonezu,iris out
196,197,NEW,2,181,NaN,1062,636,0.049,22.0,NaN,NaN,NaN,NaN,Toby Keith,Made In America,toby keith,made in america
197,198,-62,2,136,NaN,1062,-306,0.002,NaN,NaN,NaN,NaN,22.0,Momoiro Clover Z,Kaishin No Ichigeki,momoiro clover z,kaishin no ichigeki
198,199,NEW,9,53,NaN,1061,229,0.024,NaN,NaN,NaN,NaN,NaN,Angelina Mango,Canto d’amore,angelina mango,canto d’amore
199,200,-21,73,11,NaN,1057,-89,0.261,63.0,82.0,NaN,NaN,NaN,Eddie Dalton,Somewhere Along The Way,eddie dalton,somewhere along the way

In [39]:
df[df['Artist_clean'].str.contains(r'\bft\.?\b|\bfeat\.?\b|\bfeaturing\b|&', regex=True, na=False)]

,Pos,P+,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP,Artist,Title,Artist_clean,Title_clean
0,1,=,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0,Shakira & Burna Boy,Dai Dai,shakira & burna boy,dai dai
1,2,+2,44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN,"HUGEL, Imael Angel & Ultra Naté",Movin' To The Sun,"hugel, imael angel & ultra naté",movin' to the sun
3,4,-2,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0,Madonna & Sabrina Carpenter,Bring Your Love,madonna & sabrina carpenter,bring your love
11,12,+4,2,12,NaN,6842,816,0.013,120.0,34.0,40.0,43.0,NaN,Madonna & Martin Garrix,Bizarre,madonna & martin garrix,bizarre
14,15,-6,4,9,NaN,6471,-1245,0.030,160.0,4.0,27.0,3.0,NaN,Snow Patrol & Kylie Minogue,These Alarms,snow patrol & kylie minogue,these alarms
17,18,+5,121,1,(x2),5989,888,0.834,NaN,23.0,5.0,33.0,NaN,Bebe Rexha & Faithless,New Religion,bebe rexha & faithless,new religion
19,20,-3,339,1,(x112),5838,292,5.287,124.0,66.0,73.0,39.0,55.0,"HUNTR/X, EJAE, AUDREY NUNA, REI AMI & KPop Dem...",Golden,"huntr/x, ejae, audrey nuna, rei ami & kpop dem...",golden
20,21,+3,192,17,NaN,5829,745,0.615,NaN,169.0,9.0,NaN,NaN,HUGEL & SOLTO (FR),Jamaican,hugel & solto (fr),jamaican
29,30,-15,32,10,NaN,4700,-1460,0.204,NaN,31.0,8.0,50.0,NaN,"David Guetta, Alok & Stick Figure",Run Run River,"david guetta, alok & stick figure",run run river
33,34,-13,9,15,NaN,4098,-1226,0.044,182.0,58.0,35.0,142.0,NaN,"DJ Goja, Jason Derulo & Melody",Mi Chico,"dj goja, jason derulo & melody",mi chico
34,35,-2,125,7,NaN,3940,-492,0.683,85.0,70.0,63.0,83.0,NaN,Tame Impala & JENNIE,Dracula,tame impala & jennie,dracula
37,38,=,27,36,NaN,3890,144,0.084,NaN,NaN,3.0,NaN,NaN,"KITSCHKRIEG, Blumengarten & Shirin David",Gut Genug,"kitschkrieg, blumengarten & shirin david",gut genug
49,50,+1,259,30,NaN,3086,-30,0.732,NaN,14.0,NaN,10.0,NaN,Sam Fender & Olivia Dean,Rein Me In,sam fender & olivia dean,rein me in
52,53,+24,72,26,NaN,2903,690,0.205,19.0,NaN,NaN,66.0,NaN,Ella Langley & Morgan Wallen,I Can't Love You Anymore,ella langley & morgan wallen,i can't love you anymore
58,59,-11,509,23,NaN,2796,-403,1.324,29.0,134.0,NaN,25.0,NaN,Ella Langley & Riley Green,you look like you love me,ella langley & riley green,you look like you love me
77,78,+54,23,3,(x1),2194,741,0.137,NaN,96.0,105.0,188.0,NaN,"Andrea Bocelli, David Guetta, EJAE & Megan The...",DNA,"andrea bocelli, david guetta, ejae & megan the...",dna
80,81,+83,219,22,NaN,2177,989,0.625,NaN,163.0,193.0,NaN,NaN,Disney & Shakira,Zoo,disney & shakira,zoo
84,85,+13,9,50,NaN,1980,219,0.025,NaN,NaN,14.0,NaN,NaN,Andreas Gabalier & Pietro Basile,UNA CANZONE PER TE,andreas gabalier & pietro basile,una canzone per te
86,87,+152,150,22,NaN,1943,1025,0.402,NaN,116.0,NaN,NaN,NaN,Dave & Tems,Raindance,dave & tems,raindance
92,93,+8,16,32,NaN,1866,122,0.047,NaN,29.0,38.0,NaN,NaN,Chaka Khan & Snoop Dogg,Boogie's in My Soul,chaka khan & snoop dogg,boogie's in my soul
97,98,-6,13,92,NaN,1782,-120,0.041,NaN,NaN,42.0,NaN,NaN,Topic & Becky G,Sorry Papi,topic & becky g,sorry papi
123,124,+53,27,102,NaN,1498,344,0.064,NaN,59.0,NaN,NaN,NaN,Prospa & Cloonee,Free Your Mind,prospa & cloonee,free your mind
134,135,-49,686,1,(x39),1383,-666,7.557,NaN,196.0,NaN,110.0,NaN,Lady Gaga & Bruno Mars,Die With A Smile,lady gaga & bruno mars,die with a smile
139,140,NEW,1,140,NaN,1366,655,0.002,NaN,NaN,NaN,NaN,NaN,Anirudh Ravichander & Heisenberg,One Name,anirudh ravichander & heisenberg,one name
141,142,-19,2,123,NaN,1352,-151,0.003,NaN,NaN,NaN,NaN,NaN,Gianna Nannini & Marracash,AMERICA INC.,gianna nannini & marracash,america inc.
148,149,+43,721,28,NaN,1327,223,1.624,NaN,NaN,51.0,NaN,NaN,Ricchi & Poveri,Sarà perché ti amo,ricchi & poveri,sarà perché ti amo
149,150,-61,2,89,NaN,1320,-650,0.003,NaN,NaN,12.0,NaN,NaN,Capital Bra & Samra,Ghetto Superstars,capital bra & samra,ghetto superstars
155,156,+4,6,42,NaN,1276,69,0.013,NaN,NaN,NaN,NaN,NaN,THE 8 & VERNON,singasong,the 8 & vernon,singasong
164,165,NEW,2,165,NaN,1217,495,0.009,15.0,NaN,NaN,NaN,NaN,Brooks & Dunn,Only in America,brooks & dunn,only in america
173,174,-58,9,65,NaN,1168,-395,0.016,NaN,NaN,70.0,NaN,NaN,"HUGEL, French Montana, David Guetta & Aidan Ma...",Shine,"hugel, french montana, david guetta & aidan ma...",shine
174,175,+50,1,175,NaN,1149,174,0.002,NaN,NaN,NaN,NaN,NaN,Showtek & Kate Ryan,Ella Elle L'a,showtek & kate ryan,ella elle l'a
181,182,-29,16,31,NaN,1106,-145,0.061,NaN,27.0,NaN,NaN,NaN,Calvin Harris & Jazzy,Satisfy,calvin harris & jazzy,satisfy
182,183,+26,8,69,NaN,1105,76,0.016,115.0,NaN,NaN,NaN,NaN,Gravel & Grace,Sit With Me Lord,gravel & grace,sit with me lord
183,184,NEW,13,157,NaN,1104,365,0.075,NaN,NaN,NaN,NaN,NaN,"Serena Brancale, Levante & DELIA",AL MIO PAESE,"serena brancale, levante & delia",al mio paese
184,185,-24,17,44,NaN,1104,-89,0.031,20.0,NaN,NaN,NaN,NaN,Lee Greenwood & Drew Jacobs,God Bless The U.S.A.,lee greenwood & drew jacobs,god bless the u.s.a.
185,186,NEW,2,165,NaN,1104,1104,0.002,NaN,NaN,NaN,NaN,20.0,"EBiDAN Ebisu Gakuen Boys Club, chotokkyu, M!LK...",Yes Tokyo,"ebidan ebisu gakuen boys club, chotokkyu, m!lk...",yes tokyo
191,192,-111,7,7,NaN,1079,-1027,0.037,NaN,NaN,NaN,NaN,NaN,Madonna & Feid,Read My Lips,madonna & feid,read my lips

In [ ]:
df['Artist_clean'] = df['Title_clean'].str.replace(r'\bft\.?\b', 'feat', regex=True)
df['Artist_clean'] = df['Title_clean'].str.replace(r'\bfeaturing\b', 'feat', regex=True)

df

,Pos,P+,Days,Pk,(x?),Pts,Pts+,TPts,US,UK,DE,AU,JP,Artist,Title,Artist_clean,Title_clean
0,1,=,51,1,(x14),17300,955,0.686,33.0,6.0,4.0,38.0,42.0,Shakira & Burna Boy,Dai Dai,shakira & burna boy,dai dai
1,2,+2,44,2,(x4),13453,-252,0.437,59.0,3.0,2.0,7.0,NaN,"HUGEL, Imael Angel & Ultra Naté",Movin' To The Sun,"hugel, imael angel & ultra naté",movin' to the sun
2,3,+4,2,3,(x1),11086,172,0.022,60.0,9.0,28.0,6.0,NaN,Madonna,Danceteria,madonna,danceteria
3,4,-2,57,1,(x4),10573,-4266,0.342,31.0,15.0,15.0,58.0,195.0,Madonna & Sabrina Carpenter,Bring Your Love,madonna & sabrina carpenter,bring your love
4,5,+3,64,3,(x3),9671,-952,0.611,17.0,8.0,16.0,2.0,NaN,Robyn,Dancing On My Own,robyn,dancing on my own
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,NEW,201,28,NaN,1066,1066,0.391,NaN,NaN,NaN,NaN,27.0,Kenshi Yonezu,IRIS OUT,kenshi yonezu,iris out
196,197,NEW,2,181,NaN,1062,636,0.049,22.0,NaN,NaN,NaN,NaN,Toby Keith,Made In America,toby keith,made in america
197,198,-62,2,136,NaN,1062,-306,0.002,NaN,NaN,NaN,NaN,22.0,Momoiro Clover Z,Kaishin No Ichigeki,momoiro clover z,kaishin no ichigeki
198,199,NEW,9,53,NaN,1061,229,0.024,NaN,NaN,NaN,NaN,NaN,Angelina Mango,Canto d’amore,angelina mango,canto d’amore
199,200,-21,73,11,NaN,1057,-89,0.261,63.0,82.0,NaN,NaN,NaN,Eddie Dalton,Somewhere Along The Way,eddie dalton,somewhere along the way

In [40]:
df.dtypes

Pos               int64
P+                  str
Days              int64
Pk                int64
(x?)                str
Pts               int64
Pts+              int64
TPts            float64
US              float64
UK              float64
DE              float64
AU              float64
JP              float64
Artist              str
Title               str
Artist_clean        str
Title_clean         str
dtype: object